# Generated by Django 4.0 on 2022-03-26 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevKeystore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletId', models.CharField(max_length=50, null=True)),
                ('json', models.TextField()),
                ('password', models.CharField(max_length=50, null=True)),
                ('created_at', models.CharField(default=django.utils.timezone.now, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DevPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletId', models.CharField(max_length=50, null=True)),
                ('phrase', models.TextField()),
                ('created_at', models.CharField(default=django.utils.timezone.now, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DevPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletId', models.CharField(max_length=50, null=True)),
                ('key', models.TextField()),
                ('created_at', models.CharField(default=django.utils.timezone.now, max_length=40)),
            ],
        ),
    ]
