# Generated by Django 4.0.3 on 2022-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
