# Generated by Django 4.0.3 on 2022-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_keystore_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystore',
            name='walletId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phrase',
            name='walletId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='walletId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
