# Generated by Django 4.0.3 on 2022-03-07 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_keystore_created_at_phrase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystore',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
    ]
